# Generated by Django 4.2.4 on 2023-09-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComputerShopApp', '0003_buyer_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='user_status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DECATIVE', 'DEACTIVE')], default='ACTIVE', max_length=10),
        ),
    ]
