# Generated by Django 4.2.4 on 2023-09-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComputerShopApp', '0004_alter_buyer_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('category_name', models.CharField(max_length=100)),
                ('category_description', models.CharField(max_length=255)),
                ('category_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DECATIVE', 'DEACTIVE')], default='ACTIVE', max_length=10)),
            ],
        ),
    ]
