# Generated by Django 4.2.4 on 2023-09-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComputerShopApp', '0005_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
